### ISSUE TITLE
Outdated server version

### ISSUE THREAD

**Issue by MegaTKC** [WaterdogPE/Waterdog#3]
**Version of Waterdog**
v1.16.0.210
**Expected Behavior**
I should be able to go into the server without issues.
**Actual Behavior**
The server said "Timed out" "Unable to connect to world"
**Crashdump, Backtrace or Other Files**

**Describe the bug**
The proxy was out dated and I couldn't join the server.
**To Reproduce**

Download Powernukkit 1.16.0.220 and run it. Run the latest version of waterdog. Join the waterdog proxy.
**Screenshots**
None

**Server software used:**
Powernukkit

**Additional context**
Can you please add a 1.16.220 version for Minecraft PE?

**Comment by Alemiz112** [comment]
The Waterdog was already updated.

**Comment by MegaTKC** [comment]
Thank you for helping me! I appreciate your work on the waterdog project. I will star it. I didn't know it happened so quickly.
