### ISSUE TITLE
Support for MCBE 1.17.0 / Protocol 440

### ISSUE THREAD

**Issue by AlicanCopur** [WaterdogPE/Waterdog#6]
WaterdogPE updated, but there are still people using Waterdog :)

**Comment by BroccoliGG** [comment]
same for me

**Comment by Alemiz112** [comment]
Waterdog update is still planed, but it is not high priority at the moment. Update will be out once I will find enough time to create patches.

**Comment by Altamash347** [comment]
So when will it come out?

**Comment by Alemiz112** [comment]
It will be out when it will be out.
