### ISSUE TITLE
InitialHandler - encountered exception java.lang.ExceptionInInitializerError: null When Connecting To Waterdog

### ISSUE THREAD

**Issue by KygekDev** [WaterdogPE/Waterdog#7]
**Version of Waterdog**
Version git:Waterdog-Bootstrap:1.15-SNAPSHOT:643fccc:25

**Expected Behavior**
Clients (players) should be able to connect to the server without any errors, in this case connecting to the `lobby` server (see **Additional context** section for detailed explanation).

**Actual Behavior**
Server Console: An error occurred when a player was connecting to the Waterdog proxy (`InitialHandler - encountered exception java.lang.ExceptionInInitializerError: null`).
Client: A message saying "Disconnected from Server" appeared when the client tried to connect to the Waterdog proxy.

**Crashdump, Backtrace or Other Files**
Waterdog Logs: https://hastebin.com/yobaqayede.log

**Describe the bug**
An error occurred in the console when a player connects to the Waterdog proxy and a message saying "Disconnected from Server" appears in the client.

**To Reproduce**
- Prepare a Windows 10 machine and an Android device with Minecraft: Bedrock Edition installed.
- Setup a PocketMine-MP server with `xbox-auth` turned off and port set to 19134 in the `server.properties` file.
- Download the Waterdog proxy directly from [here](https://jenkins.waterdog.dev/job/Waterdog/job/Waterdog/job/master-zlib/lastSuccessfulBuild/artifact/Waterfall-Proxy/bootstrap/target/Waterdog.jar) and run the JAR file in [`start.cmd`](https://docs.waterdog.dev/books/waterdogpe-setup/page/starting-waterdog#bkmrk-windows).
- Change the contents of the generated `config.yml` file to [this](https://hastebin.com/zodiheboqa.yaml).
- Connect to the Waterdog proxy using an Android device connected to the same LAN as the Windows 10 machine.

**Screenshots**
Client:
![Screenshot_20210627-185626_Minecraft](https://user-images.githubusercontent.com/68368066/123542253-367c5800-d77b-11eb-9ad1-a19b2460e9d3.jpg)

**Server software used:**
PocketMine-MP

**Additional context**
The `lobby` server is set in the [`config.yml` file](https://hastebin.com/zodiheboqa.yaml) and declared as the only server at `priorities` inside `listeners`.

**Comment by TobiasGrether** [comment]
What java version are you using to run Waterdog?

**Comment by KygekDev** [comment]
> What java version are you using to run Waterdog?

java version "16.0.1" 2021-04-20
Java(TM) SE Runtime Environment (build 16.0.1+9-24)
Java HotSpot(TM) 64-Bit Server VM (build 16.0.1+9-24, mixed mode, sharing)

**Comment by TobiasGrether** [comment]
Waterdog isn't tested for 1.16 yet. Please use it with Java 8 or 11 until we officially announce support.

**Comment by KygekDev** [comment]
Thanks, it works correctly now using Java 8.
